### ISSUE TITLE
Russian only?

### ISSUE THREAD

**Issue by RaulTsc** [WebbyLab/itsquiz-wall#53]
Nevermind :)

**Comment by krambertech** [comment]
Thank you, our fault. 
You can sign in [http://app.itsquiz.com/en/login](http://app.itsquiz.com/en/login) and use Quiz Wall embedded in UI. In this case language will be English. You can change it in your settings later.

**Comment by RaulTsc** [comment]
When trying to log in with Facebook/Google/Github I get

```
InternalOAuthError: Failed to fetch user profile (status: 401 data: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"})
   at /home/itsquiz/itsquiz-be/node_modules/passport-github2/lib/strategy.js:98:19
   at passBackControl (/home/itsquiz/itsquiz-be/node_modules/passport-github2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/itsquiz/itsquiz-be/node_modules/passport-github2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:117:20)
   at IncomingMessage.wrapped (/home/itsquiz/itsquiz-be/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
   at IncomingMessage.wrappedEmit [as emit] (/home/itsquiz/itsquiz-be/node_modules/newrelic/lib/transaction/tracer/index.js:186:46)
   at _stream_readable.js:944:16
   at wrapped (/home/itsquiz/itsquiz-be/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
   at process._tickDomainCallback [as _tickCallback] (node.js:492:13)
```

Refreshing and trying to log in again (will no longer be asked to authorize access) will work just fine.

**Comment by RaulTsc** [comment]
Also, thanks a lot for open-sourcing this. It's great :+1:
